CREATE TABLE [dbo].[Author]
(
	[Id]	BIGINT				IDENTITY(1,1)	NOT NULL,
	[Name]	NVARCHAR(64)						NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] DESC)
)

GO

CREATE NONCLUSTERED INDEX [Name_IX]
	ON [dbo].[Author]([Name])
