CREATE TABLE [dbo].[BookAuthor]
(
	[BookId]	INT NOT NULL,
	[AuthorId]	INT NOT NULL,

	FOREIGN KEY (BookId) REFERENCES Book(Id) ON DELETE CASCADE,
	FOREIGN KEY (AuthorId) REFERENCES Author(Id) ON DELETE CASCADE
)
