CREATE TABLE [dbo].[BookAuthor]
(
	[BookId]	BIGINT NOT NULL,
	[AuthorId]	BIGINT NOT NULL,

	CONSTRAINT [PK_BookAuthor] PRIMARY KEY CLUSTERED ([BookId] ASC, [AuthorId] ASC),
	FOREIGN KEY (BookId) REFERENCES Book(Id) ON DELETE CASCADE,
	FOREIGN KEY (AuthorId) REFERENCES Author(Id) ON DELETE CASCADE
)
